# Generated by Django 2.1 on 2020-07-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
